language: ruby
env: COVERAGE=true
rvm:
  - 2.1.2
cache: bundler
before_script:
  - cp ./config/database.yml.example ./config/database.yml
script:
  - RAILS_ENV=test bin/rake db:setup
  - RAILS_ENV=test bin/rake db:schema:load
  - bin/rspec
addons:
  code_climate:
    repo_token: c94151dfd6c4fd28f3846fc595400381ed1d786d9ab2902ff12d5deeb7d0de75
  postgresql: 9.3
