development: &development
  adapter: postgresql
  encoding: unicode
  database: cellar_development
  pool: <%= ENV['SIDEKIQ_CONCURRENCY'] || 5 %>

test:
  <<: *development
  database: cellar_test

# production: NOT HERE because Heroku uses ENV['DATABASE_URL']
