development:
  adapter: postgresql
  encoding: unicode
  database: cellar_development

test:
  adapter: postgresql
  encoding: unicode
  database: cellar_test

production:
  adapter: postgresql
  encoding: unicode
  database: cellar_production
